name: Sync Branches

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name "sandeshk"
          git config --global user.email "v-skundar@microsoft.com"

      - name: Create or checkout secondary branch
        run: |
          git fetch
          git checkout secondary || git checkout -b secondary
          git merge origin/secondary || true  # Merge changes from remote secondary if it exists

      - name: Merge main into secondary
        run: |
          git merge main --allow-unrelated-histories -m "Sync changes from main to secondary" || true

      - name: Resolve conflicts and commit
        run: |
          git checkout --theirs . # Accept changes from 'main'
          git add .
          git commit -m "Resolved merge conflicts from main into secondary"
        continue-on-error: true

      - name: Push changes
        run: |
          git push origin secondary
       
