name: Sync Branches

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create or checkout secondary branch
        run: |
          git fetch
          git checkout secondary || git checkout -b secondary
          git merge origin/secondary || true  # Merge changes from remote secondary if it exists

      - name: Sync updat